### ISSUE TITLE
performance / troughtput question

### ISSUE THREAD

**Issue by zenvdeluca** [stmosher/AWS_VPC_with_CSR1000v_v2.0#1]
Hi

I am running similar setup where I use terraform to provision a multi region DMVPN across AWS.

inside US my max troughput was about 600mbps, but US <=> Europe is no more than 150-200mbps.

do you have any better experience than above mentioned ?

**Comment by stmosher** [comment]
Hi,
I do have experience with high delay comms. Usually this is an issue within networked apps where one side must communication with the other and wait for a response. It's an issue in the OSI session layer which is greatly compounded when apps are "chatty" over high delay networks (propagation in your case). Another issue is often at the OSI transport layer where TCP does the same thing. What can help with TCP is larger TCP window sizes and selective acknowledgements. A product like Cisco WAAS can help with application chattiness by proxying redundant applicaition communication locally and then only transmiting important info over the long haul and by optimizing TCP flows.
HTH,
Steve
