### ISSUE TITLE
issues on ansible ios config module

### ISSUE THREAD

**Issue by jsoyee** [stmosher/AWS_VPC_with_CSR1000v_v2.0#2]
Hi @stmosher thanks a lot for sharing this great tool, i got some errors from executing ansible ios_config module which end up with incomplete configuration if we just ignore them.
particularly for things like below, i am wondering how you address this. 
TASK [debug] *************************************************************************************
ok: [34.211.107.134] => {
    "changed": false,
    "results": {
        "changed": false,
        "command": "crypto map mymap 10 ipsec-isakmp",
        "failed": true,
        "msg": "crypto map mymap 10 ipsec-isakmp\r\n% NOTE: This new crypto map will remain disabled until a peer\r\n\tand a valid access list have been configured.\r\nip-10-20-21-5(config-crypto-map)#",
        "rc": 1
    }
}

**Comment by stmosher** [comment]
Hi @jsoyee, I ran into this in ansible 2.3.0. It works fine with Ansible 2.2.1.0. 
When Ansible receives a warning about needing an identity statement in crypto configs, Ansible is considering it a failure and not completing the configuration. There was an issue open in GitHub for an Ansible 1.X version on this, it was fixed, and now it's back again in version 2.3.0. When I get some time, I'll open an issue with Ansible (I need to find the original issue again).
For now running Ansible version 2.2.1.0 works fine.
I'll test with version 2.2.3 soon

**Comment by stmosher** [comment]
Hi  @jsoyee, Looks like the problem was the way Ansible 2.3 handled IOS notifications that began with a "%". The issue has been fixed and closed. For more information see below
https://github.com/ansible/ansible/issues/23771
https://github.com/ansible/ansible/pull/23858

**Comment by stmosher** [comment]
FYI -I was able to fix the issue in my version 2.3.0 of Anisble by:
/usr/lib/python2.7/dist-packages/ansible/plugins/terminal$ sudo ios.py
Then comment out line 38, e.g.:
snip
36 terminal_stderr_re = [
37      re.compile(r"% ?Error"),
38        #re.compile(r"^% \w+", re.M),
snip
Now it works. See below from output:
ow works
snip
       "replace": "line",
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "updates": [
        "crypto isakmp profile TESTisakmp-profTEST",
        "keyring internet-key",
        "match identity address 0.0.0.0 internet-vrf"
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************
34.225.201.89              : ok=1    changed=1    unreachable=0    failed=0
snip
